# Generated by Django 6.1.1 on 2026-09-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctor',
            table='doctor',
        ),
    ]
