# Generated by Django 6.1.1 on 2026-09-18 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_doctor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
        migrations.AlterModelTable(
            name='bill',
            table='bill',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='medicalrecord',
            table='medicalrecord',
        ),
        migrations.AlterModelTable(
            name='medicine',
            table='medicine',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
        migrations.AlterModelTable(
            name='prescription',
            table='prescription',
        ),
    ]
